### PR TITLE
140 dummy data

### PR DESCRIPTION
**Pull request by camboucher**
I populated the exampleData.js file with records fitting the schemas. The only one still missing is orders, which might be a little more complicated to figure out since it will need to match the seller / buyer / product records. I want to get this pulled and merged with the dev branch though so everyone can start using the dummy data on the front-end. @Yuki-1025 @pjones2012 @thejasondye

### CODE REVIEW

**Review by thejasondye — APPROVED** [review]
Git is showing the gitignore as a conflict, but it looks fine to me

**Comment by thejasondye** [comment]
Although, I'm not sure how this data will work since it isn't nested into Seller's data ...

**Comment by thejasondye** [comment]
@camboucher You may want to do a quick pull and merge, then try this again?  Not sure why it's giving this conflict.

**Comment by camboucher** [comment]
Ok - looks like the merge is resolved. The products / services are nested into the sellers data, so we could remove the unnested versions. I'm not sure exactly how people will use the dummy data and it's much easier to delete later than recreate it.

**Pull request merged**
